In [4]:
from IPython.display import Image 
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
import seaborn as sns

pd.set_option('display.max_columns', None)


df_schools = pd.read_spss("./data/CY07_MSU_SCH_QQQ.sav")

df_paises = pd.read_csv("./data/paises.csv")

In [2]:
df_schools.info()
df_schools.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21903 entries, 0 to 21902
Columns: 197 entries, CNTRYID to BOOKID
dtypes: category(190), float64(4), object(3)
memory usage: 7.9+ MB

,CNTRYID,CNT,CNTSCHID,CYC,NatCen,Region,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST,SC001Q01TA,SC013Q01TA,SC016Q01TA,SC016Q02TA,SC016Q03TA,SC016Q04TA,SC017Q01NA,SC017Q02NA,SC017Q03NA,SC017Q04NA,SC017Q05NA,SC017Q06NA,SC017Q07NA,SC017Q08NA,SC161Q01SA,SC161Q02SA,SC161Q03SA,SC161Q04SA,SC161Q05SA,SC162Q01SA,SC155Q01HA,SC155Q02HA,SC155Q03HA,SC155Q04HA,SC155Q05HA,SC155Q06HA,SC155Q07HA,SC155Q08HA,SC155Q09HA,SC155Q10HA,SC155Q11HA,SC156Q01HA,SC156Q02HA,SC156Q03HA,SC156Q04HA,SC156Q05HA,SC156Q06HA,SC156Q07HA,SC156Q08HA,SC011Q01TA,SC012Q01TA,SC012Q02TA,SC012Q03TA,SC012Q04TA,SC012Q05TA,SC012Q06TA,SC012Q07TA,SC042Q01TA,SC042Q02TA,SC154Q01HA,SC154Q02WA,SC154Q03WA,SC154Q04WA,SC154Q05WA,SC154Q06WA,SC154Q07WA,SC154Q08WA,SC154Q09HA,SC154Q10WA,SC154Q11HA,SC036Q01TA,SC036Q02TA,SC036Q03NA,SC037Q01TA,SC037Q02TA,SC037Q03TA,SC037Q04TA,SC037Q05NA,SC037Q06NA,SC037Q07TA,SC037Q08TA,SC037Q09TA,SC037Q10NA,SC165Q01HA,SC165Q02HA,SC165Q03HA,SC165Q04HA,SC165Q05HA,SC165Q06HA,SC165Q07HA,SC165Q08HA,SC165Q09HA,SC165Q10HA,SC166Q02HA,SC166Q03HA,SC166Q05HA,SC166Q06HA,SC167Q01HA,SC167Q02HA,SC167Q03HA,SC167Q04HA,SC167Q05HA,SC167Q06HA,SC158Q01HA,SC158Q02HA,SC158Q04HA,SC158Q07HA,SC158Q08HA,SC158Q09HA,SC158Q12HA,SC061Q01TA,SC061Q02TA,SC061Q03TA,SC061Q04TA,SC061Q05TA,SC061Q11HA,SC061Q06TA,SC061Q07TA,SC061Q08TA,SC061Q09TA,SC061Q10TA,SC002Q01TA,SC002Q02TA,SC048Q01NA,SC048Q02NA,SC048Q03NA,SC004Q01TA,SC004Q02TA,SC004Q03TA,SC004Q04NA,SC004Q05NA,SC004Q06NA,SC004Q07NA,SC018Q01TA01,SC018Q01TA02,SC018Q02TA01,SC018Q02TA02,SC018Q05NA01,SC018Q05NA02,SC018Q06NA01,SC018Q06NA02,SC018Q07NA01,SC018Q07NA02,SC025Q01NA,SC159Q01HA,SC003Q01TA,SC053Q01TA,SC053Q02TA,SC053Q03TA,SC053Q04TA,SC053Q12IA,SC053Q13IA,SC053Q09TA,SC053Q10TA,SC053Q14IA,SC053Q15IA,SC053Q16IA,SC053D11TA,SC150Q01IA,SC150Q02IA,SC150Q03IA,SC150Q04IA,SC150Q05IA,SC164Q01HA,SC064Q01TA,SC064Q02TA,SC064Q03TA,SC064Q04NA,SC152Q01HA,SC160Q01WA,SC052Q01NA,SC052Q02NA,SC052Q03HA,PRIVATESCH,SCHLTYPE,STRATIO,SCHSIZE,RATCMP1,RATCMP2,TOTAT,PROATCE,PROAT5AB,PROAT5AM,PROAT6,CLSIZE,CREACTIV,EDUSHORT,STAFFSHORT,STUBEHA,TEACHBEHA,SCMCEG,W_SCHGRNRABWT,W_FSTUWT_SCH_SUM,SENWT,VER_DAT,BOOKID
0,Albania,Albania,800002.0,07MS,Albania,Albania,ALB - stratum 09: Rural / Center / Public,Albania,No,Computer,Albanian,"A village, hamlet or rural area (fewer than 3 ...",A public school (Managed by a public education...,95.0,0.0,5.0,0.0,Not at all,Not at all,Not at all,Not at all,To some extent,To some extent,To some extent,To some extent,Not checked,Not checked,Checked,Not checked,Not checked,Career guidance is formally scheduled into stu...,Disagree,Disagree,Disagree,Strongly disagree,Strongly disagree,Agree,Agree,Agree,Disagree,Agree,Agree,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,There are no other schools in this area that c...,Always,Always,Never,Never,Never,Always,Sometimes,Not for any subjects,Not for any subjects,Yes,Yes,Yes,No,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes,Yes,"Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...",Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,Yes,Shared among some of them,Shared among many of them,Shared among many of them,Shared among all or almost all of them,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Very little,Very little,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,NaN,NaN,0.0,0.0,40.0,NaN,7.0,0.0,0.0,0.0,1.0,1.0,26.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,98.0,Yes,16-20 students,No,No,No,No,Yes,Yes,Yes,Yes,Yes,No,Yes,Albania : Retraction of the rope-No,No,No,No,No,No,0.0,70.0,70.0,100.0,0.0,No,NaN,No,No,No,public,Public,NaN,NaN,NaN,0.0000,26.0,0.0000,0.0000,0.1154,0.0,16-20 students,1.0,1.2478,-1.4551,-1.1797,-2.0409,-1.0391,7.98891,115.10603,24.81933,09MAY19:11:20:57,NaN
1,Albania,Albania,800003.0,07MS,Albania,Albania,ALB - stratum 09: Rural / Center / Public,Albania,No,Computer,Albanian,"A village, hamlet or rural area (fewer than 3 ...",A public school (Managed by a public education...,NaN,NaN,100.0,NaN,Not at all,Not at all,Not at all,Not at all,Very little,To some extent,Very little,To some extent,Checked,Not checked,Not checked,Not checked,Not checked,NaN,Disagree,Disagree,Disagree,Disagree,Disagree,Agree,Agree,Disagree,Strongly disagree,Disagree,Agree,No,No,No,Yes,No,Yes,No,No,There is one other school in this area that co...,Sometimes,Sometimes,Always,Sometimes,Always,Always,NaN,Not for any subjects,For some subjects,No,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,Yes,No,No,Yes,"Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative",No,"Yes, this is mandatory, e.g. based on district...",No,"Yes, based on school initiative",Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Shared among many of them,Shared among many of them,Shared among many of them,Shared among many of them,No,No,No,No,Yes,No,No,No,No,No,No,No,No,A lot,A lot,To some extent,A lot,To some extent,To some extent,A lot,A lot,To some extent,To some extent,A lot,NaN,NaN,NaN,5.0,70.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,6.0,NaN,6.0,NaN,2.0,NaN,2.0,NaN,0.0,NaN,19.0,No,15 students or fewer,No,No,No,No,No,No,Yes,No,No,No,No,Albania : Retraction of the rope-No,Yes,No,No,Yes,Yes,NaN,NaN,NaN,NaN,NaN,Yes,Enrichment only,No,No,No,public,Public,NaN,NaN,NaN,NaN,6.0,1.0000,0.3333,0.3333,0.0,15 students or fewer,1.0,0.6221,-1.4551,2.1196,2.5150,-1.0542,6.50492,26.01970,20.20900,09MAY19:11:20:57,NaN
2,Albania,Albania,800004.0,07MS,Albania,Albania,ALB - stratum 11: Rural / South / Public,Albania,No,Computer,Albanian,"A village, hamlet or rural area (fewer than 3 ...",A public school (Managed by a public education...,100.0,0.0,0.0,0.0,Not at all,Not at all,Not at all,Not at all,Very little,To some extent,Very little,Very little,Not checked,Not checked,Checked,Not checked,Not checked,Career guidance is formally scheduled into stu...,Disagree,Agree,Strongly disagree,Strongly disagree,Strongly disagree,Agree,Agree,Strongly disagree,Strongly disagree,Strongly disagree,Agree,Yes,Yes,Yes,No,Yes,No,Yes,Yes,There is one other school in this area that co...,Always,Always,Always,Always,Always,Always,Always,Not for any subjects,For all subjects,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,"Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...",Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,No,Yes,Shared among all or almost all of them,Shared among all or almost all of them,Shared among all or almost all of them,Shared among all or almost all of them,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Very little,Very little,Very little,Not at all,Not at all,Very little,Very little,Very little,Not at all,Not at all,Very little,109.0,96.0,NaN,2.0,85.0,37.0,0.0,0.0,0.0,0.0,2.0,0.0,21.0,0.0,21.0,0.0,11.0,0.0,10.0,0.0,0.0,0.0,100.0,No,16-20 students,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Albania : Retraction of the rope-No,Yes,Yes,Yes,Yes,Yes,1.0,62.0,80.0,60.0,90.0,Yes,Enrichment only,Yes,Yes,Yes,public,Public,9.7619,205.0,0.0000,NaN,21.0,1.0000,0.5238,0.4762,0.0,16-20 students,2.0,0.4591,-1.4551,-0.6199,-0.4415,0.9042,6.64198,99.62974,20.63480,09MAY19:11:20:57,NaN
3,Albania,Albania,800005.0,07MS,Albania,Albania,ALB - stratum 07: Rural / North / Public,Albania,No,Computer,Albanian,A small town (3 000 to about 15 000 people),A public school (Managed by a public education...,100.0,0.0,0.0,0.0,To some extent,To some extent,Very little,To some extent,A lot,To some extent,Very little,Very little,Not checked,Not checked,Checked,Not checked,Not checked,Career guidance is sought voluntarily by students,Disagree,Agree,Disagree,Disagree,Disagree,Agree,Agree,Agree,Disagree,Agree,Disagree,No,No,Yes,Yes,Yes,No,Yes,Yes,There are two or more other schools in this ar...,Sometimes,Always,Sometimes,Always,Always,Always,Sometimes,Not for any subjects,For some subjects,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,"Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...",Yes,Yes,Yes,No,Yes,No,Yes,Yes,No,Yes,Shared among many of them,Shared among many of them,Shared among some of them,Shared among many of them,No,Yes,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Very little,Very little,To some extent,Not at all,Not at all,Very little,Very little,Very little,Very little,Not at all,Very little,NaN,NaN,NaN,2.0,25.0,NaN,15.0,5.0,0.0,0.0,1.0,4.0,34.0,1.0,21.0,0.0,12.0,1.0,22.0,0.0,0.0,0.0,100.0,Yes,21-25 students,No,Yes,No,Yes,Yes,No,No,Yes,Yes,Yes,No,Albania : Retraction of the rope-Yes,No,No,No,No,No,1.0,65.0,60.0,58.0,55.0,Yes,Both enrichment and remedial,No,Yes,Yes,public,Public,NaN,NaN,NaN,0.3333,34.5,0.6087,0.3623,0.6377,0.0,21-25 students,1.0,1.3065,1.2432,-0.2682,-0.0452,-1.5648,5.93762,66.50133,18.44654,09MAY19:11:20:57,NaN
4,Albania,Albania,800006.0,07MS,Albania,Albania,ALB - stratum 05: Urban / South / Public,Albania,No,Computer,Albanian,A small town (3 000 to about 15 000 people),A public school (Managed by a public education...,100.0,NaN,NaN,NaN,Not at all,Not at all,Not at all,Not at all,Very little,Very little,Not at all,Not at all,Not checked,Not checked,Checked,Not checked,Not checked,Career guidance is formally scheduled into stu...,Disagree,Strongly agree,Disagree,Disagree,Disagree,Strongly agree,Agree,Strongly agree,Strongly disagree,Disagree,Strongly agree,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,There are two or more other schools in this ar...,Always,Always,Always,Always,Always,Always,NaN,NaN,For all subjects,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, this is mandatory, e.g. based on district...","Yes, based on school initiative","Yes, based on school initiative",Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Shared among all or almost all of them,Shared among all or almost all of them,Shared among all or almost all of them,Shared among all or almost all of them,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Not at all,Very little,Not at all,Not at all,Not at all,Very little,Not at all,Not at all,Not at all,Not at all,Not at all,175.0,140.0,0.0,1.0,12.0,39.0,1.0,1.0,1.0,0.0,1.0,1.0,17.0,1.0,17.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,87.0,No,36-40 students,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Albania : Retraction of the rope-Yes,No,No,No,No,No,NaN,97.0,97.0,99.0,2.0,Yes,Both enrichment and remedial,No,No,Yes,public,Public,18.0000,315.0,0.0256,1.0000,17.5,1.0000,0.0000,0.1714,0.0,36-40 students,3.0,-0.2376,-1.4551,-1.3196,-2.0409,0.9042,14.61508,277.68645,45.40500,09MAY19:11:20:57,NaN

Añadir el código de pais a dataframe de escuelas

In [5]:
for index, pais in df_paises.iterrows():
    df_schools.loc[df_schools['CNTRYID'] == pais['name'], ['code']] = pais['code']
      
df_schools[['CNTRYID','code']].head()

   CNTRYID code
0  Albania  ALB
1  Albania  ALB
2  Albania  ALB
3  Albania  ALB
4  Albania  ALB

In [5]:
#pd.set_option('display.max_columns', None)
#df_schools.tail()

df = df_schools[['CNTRYID','SC001Q01TA', 'SC013Q01TA', 'SC016Q01TA', 'SC016Q02TA','SC016Q03TA','SC016Q04TA']].copy()

df['SC016Q01TA'] = pd.to_numeric(df['SC016Q01TA']).fillna(0)
df['SC016Q02TA'] = pd.to_numeric(df['SC016Q02TA']).fillna(0)
df['SC016Q03TA'] = pd.to_numeric(df['SC016Q03TA']).fillna(0)
df['SC016Q04TA'] = pd.to_numeric(df['SC016Q04TA']).fillna(0)



one_hot = pd.get_dummies(df[['SC001Q01TA', 'SC013Q01TA']])

df.drop(['SC001Q01TA'],axis=1, inplace=True)
df.drop(['SC013Q01TA'], axis=1, inplace=True)
df = df.join(one_hot)

columns= ['CNTRYID', 
        'Gobierno', 'Padres', 'Benefactores', 'Otros',
        'SC001Q01TA_Ciudad entre 100.000 y 1.000.000 habitantes',
        'SC001Q01TA_Gran ciudad con más de 1.000.000 habitantes',
        'SC001Q01TA_Pequeño pueblo, entre 3.000 y 15 000 habitantes',
        'SC001Q01TA_Pueblo entre 15.000 y 100.000 habitantes',
        'SC001Q01TA_Villa o área rural, menos de 3.000 habitantes',
        'Escuela privada',
        'Escuela pública']
df.columns = columns

df.head()


#df[['SC001Q01TA']].tail()

,CNTRYID,Gobierno,Padres,Benefactores,Otros,SC001Q01TA_Ciudad entre 100.000 y 1.000.000 habitantes,SC001Q01TA_Gran ciudad con más de 1.000.000 habitantes,"SC001Q01TA_Pequeño pueblo, entre 3.000 y 15 000 habitantes",SC001Q01TA_Pueblo entre 15.000 y 100.000 habitantes,"SC001Q01TA_Villa o área rural, menos de 3.000 habitantes",Escuela privada,Escuela pública
0,Albania,95.0,0.0,5.0,0.0,0,0,0,0,1,0,1
1,Albania,0.0,0.0,100.0,0.0,0,0,0,0,1,0,1
2,Albania,100.0,0.0,0.0,0.0,0,0,0,0,1,0,1
3,Albania,100.0,0.0,0.0,0.0,0,0,1,0,0,0,1
4,Albania,100.0,0.0,0.0,0.0,0,0,1,0,0,0,1

# Financiación

In [6]:
df_agrupado = df.groupby(['CNTRYID']).sum()

total_finaciacion = df_agrupado[['Gobierno', 'Padres', 'Benefactores', 'Otros']].sum(axis=1)

df_agrupado['Gobierno'] = df_agrupado['Gobierno']/total_finaciacion *100
df_agrupado['Padres'] = df_agrupado['Padres']/total_finaciacion *100
df_agrupado['Benefactores'] = df_agrupado['Benefactores']/total_finaciacion *100
df_agrupado['Otros'] = df_agrupado['Otros']/total_finaciacion * 100

total_ciudades = df_agrupado[columns[4:10]].sum(axis=1)

df_agrupado[columns[5]] = df_agrupado[columns[5]]/total_ciudades *100
df_agrupado[columns[6]] = df_agrupado[columns[6]]/total_ciudades *100
df_agrupado[columns[7]] = df_agrupado[columns[7]]/total_ciudades *100
df_agrupado[columns[8]] = df_agrupado[columns[8]]/total_ciudades *100
df_agrupado[columns[9]] = df_agrupado[columns[9]]/total_ciudades *100

total_tipo = df_agrupado[columns[10:11]].sum(axis=1)
df_agrupado[columns[10]] = df_agrupado[columns[10]]/total_ciudades *100
df_agrupado[columns[11]] = df_agrupado[columns[11]]/total_ciudades *100


df_agrupado.head()

NameError: name 'df' is not defined

In [7]:
df_agrupado.to_csv('./dato/financiacion.csv')

In [43]:

df_teacher["TC002Q01NA"] = pd.to_numeric(df_teacher['TC002Q01NA'])
df_teacher["TC007Q02NA"] = pd.to_numeric(df_teacher['TC007Q02NA'])

df_teacher[['CNTRYID','Region','TC002Q01NA','TC007Q02NA']].groupby(['CNTRYID']).mean()

NameError: name 'df_teacher' is not defined

In [16]:
df = df_schools[['CNTRYID','SC001Q01TA']].copy()

df_groupby = df.groupby(['SC001Q01TA','CNTRYID']).size().reset_index(name='counts')
df_groupby.columns = ['group','variable','value']
df_groupby.tail()

#df_groupby.to_csv('./pagina/data/tipo_centro.csv')

,group,variable,value
395,"A village, hamlet or rural area (fewer than 3 ...",United Arab Emirates,72
396,"A village, hamlet or rural area (fewer than 3 ...",United Kingdom,31
397,"A village, hamlet or rural area (fewer than 3 ...",United States,11
398,"A village, hamlet or rural area (fewer than 3 ...",Uruguay,14
399,"A village, hamlet or rural area (fewer than 3 ...",Vietnam,65

# Recursos TIC

Extracción de los datos de los recursos TIC disponibles para los alumnos.

In [27]:
df = df_schools[['CNTRYID','code','SC018Q01TA01','SC018Q01TA02','SC004Q01TA','SC004Q02TA'
                 ,'SC004Q03TA','SC004Q04NA','SC004Q05NA','SC004Q06NA','SC004Q07NA']].copy()
df.dropna(subset = ["SC004Q01TA"], inplace=True)


df['SC018Q01TA01'] = pd.to_numeric(df['SC018Q01TA01']).fillna(0)
df['SC018Q01TA02'] = pd.to_numeric(df['SC018Q01TA02']).fillna(0)
df['SC018Q01TA01'] = df['SC018Q01TA01'] + df['SC018Q01TA02']
df.drop('SC018Q01TA02', inplace=True, axis=1)


df['SC004Q01TA'] = (pd.to_numeric(df['SC004Q01TA']).fillna(0))
df['SC004Q02TA'] = pd.to_numeric(df['SC004Q02TA']).fillna(0)
df['SC004Q03TA'] = pd.to_numeric(df['SC004Q03TA']).fillna(0)
df['SC004Q04NA'] = pd.to_numeric(df['SC004Q04NA']).fillna(0)
df['SC004Q05NA'] = pd.to_numeric(df['SC004Q05NA']).fillna(0)
df['SC004Q06NA'] = pd.to_numeric(df['SC004Q06NA']).fillna(0)
df['SC004Q07NA'] = pd.to_numeric(df['SC004Q07NA']).fillna(0)


df_groupby = df.groupby(['CNTRYID'], as_index=False).mean()

df_groupby.insert(1,'code','')
for index, pais in df_paises.iterrows():
    df_groupby.loc[df_groupby['CNTRYID'] == pais['name'], ['code']] = pais['code']


columns= ['name', 
          'code',
          'Profesorado',
         'Alumnado',
         'Ordenadores',
         'Con conexión a internet',
         'Portatiles',
          'Pizarras interactivas',
          'Proyectores',
          'Ordenadores para profesores'
         ]


df_groupby.columns= columns

for col in columns:
    if col not in ['Alumnado','name','code','Profesorado','Ordenadores para profesores']:
       df_groupby[col] = df_groupby[col]/df_groupby['Alumnado']

df_groupby['Ordenadores para profesores'] = df_groupby['Ordenadores para profesores']/df_groupby['Profesorado']


df_groupby.head()

df_groupby.to_csv('./docs/data/recursostic.csv',, index=False)

# Capacidades TIC

In [40]:
df = df_schools[['CNTRYID','code','SC155Q01HA','SC155Q02HA','SC155Q03HA','SC155Q04HA'
                 ,'SC155Q05HA','SC155Q06HA','SC155Q07HA','SC155Q08HA','SC155Q09HA'
                 ,'SC155Q10HA', 'SC155Q11HA']].copy()


#df['code'] = df['SC155Q08HA'].astype('category').cat.codes


for key in df.columns:
    if key != 'CNTRYID' and key !='code':
        values = ['Strongly disagree', 'Disagree','Agree','Strongly agree']
        for i,value in enumerate(values):
            df.loc[ df[key]==value, [key+"_code"]] = i
    
df.head()

df_groupby = df.groupby(['CNTRYID'],  as_index=False).mean()

df_groupby.insert(1,'code','')
for index, pais in df_paises.iterrows():
    df_groupby.loc[df_groupby['CNTRYID'] == pais['name'], ['code']] = pais['code']

columns= ['name', 'code',
         'Dispositivos conectados a internet',
          'Ancho de banda',
          'Dispositivos para docencia',
          'Capacidad de los dispositivos',
          'Software adecuado',
          'Técnica y capacidades pedagógicas del profesorado',
          'Tiempo para preparar integrar TIC',
          'Recursos para aprender a usar dispositivos TIC',
          'Disponible plataforma de elearning',
          'Incentivos para integrar  dispositivos TIC ',
          'Personal técnico cualificado']
df_groupby.columns = columns    

    
df_groupby.head()

df_groupby.to_csv('./pagina2/data/capacidadestic.csv', index=False)